apiVersion: v1
entries:
  csi-s3:
  - apiVersion: v1
    appVersion: 0.43.7
    created: "2026-05-25T05:32:32.640830654Z"
    description: Container Storage Interface (CSI) driver for S3 volumes
    digest: d9b37df50811ca2935a51d163d5f92a16120b3421200e141740e904d818b7afa
    home: https://github.com/thxcode/k8s-csi-s3
    icon: https://raw.githubusercontent.com/yandex-cloud/geesefs/master/doc/geesefs.png
    keywords:
    - s3
    name: csi-s3
    sources:
    - https://github.com/thxcode/k8s-csi-s3/deploy/helm
    urls:
    - https://thxCode.github.io/k8s-csi-s3/charts/csi-s3-0.43.7.tgz
    version: 0.43.7
generated: "2026-05-25T05:32:32.64035252Z"
