apiVersion: v1
entries:
  csi-s3:
  - apiVersion: v1
    appVersion: 0.43.7
    created: "2026-05-25T05:52:58.526492876Z"
    description: Container Storage Interface (CSI) driver for S3 volumes
    digest: c3b206fc32ac3a65758d25a4f5391c9fe9633f6ba1004f47a26f22ebb0ae2b20
    home: https://github.com/thxcode/k8s-csi-s3
    icon: https://raw.githubusercontent.com/yandex-cloud/geesefs/master/doc/geesefs.png
    keywords:
    - s3
    name: csi-s3
    sources:
    - https://github.com/thxcode/k8s-csi-s3/deploy/helm
    urls:
    - https://thxCode.github.io/k8s-csi-s3/charts/csi-s3-0.43.7.tgz
    version: 0.43.7
generated: "2026-05-25T05:52:58.526002649Z"
